version: "3"

services:

    nginx:
        build: .
        image: ghcr.io/flavienbwk/nginx-keycloak/nginx-sso:20220304
        # Following command auto-replaces env variables in NGINX configuration
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && /usr/local/openresty/nginx/sbin/nginx -g 'daemon off;'" 
        ports:
            - 3002:3002
        volumes: 
            - ./logs:/var/log/nginx
            - ./nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
        environment:
            KEYCLOAK_INTERNAL_ENDPOINT: ${KEYCLOAK_INTERNAL_ENDPOINT}
            KEYCLOAK_EXTERNAL_ENDPOINT: ${KEYCLOAK_EXTERNAL_ENDPOINT}
            KEYCLOAK_LOGOUT_REDIRECT_URI: ${KEYCLOAK_LOGOUT_REDIRECT_URI}
            KEYCLOAK_REALM: ${KEYCLOAK_REALM}
            KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
            KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}

    postgres:
        image: postgres:12
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment: 
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
            
    keycloak:
        image: jboss/keycloak:15.1.1
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: ${POSTGRES_DB}
            DB_USER: ${POSTGRES_USER}
            DB_SCHEMA: public
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            KEYCLOAK_USER: ${KEYCLOAK_USER}
            KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        ports:
            - 3333:8080
        depends_on:
            - postgres

    app_1:
        image: nginx:1.21.6

volumes:
    postgres_data:
