version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run: |
          docker-compose build