version: 2
jobs:
  build:
    resource_class: small
    docker:
      - image: docker:20.10.12-dind
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              gcc make py-pip
            pip install \
              docker-compose
      - run:
          name: Build
          command: |
            cp .env.example .env
            docker-compose build