name: Docker build of nginx-keycloak

on: [push]

jobs:

  docker-build:
    name: Ubuntu 22.04 build of nginx-keycloak
    runs-on: ubuntu-22.04

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
            
      - name: Docker-compose build
        run: |
          docker compose build
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push nginx image to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/flavienbwk/nginx-keycloak/nginx-sso:$(grep -oP "(?<=image: ghcr.io/flavienbwk/nginx-keycloak/nginx-sso:).*" docker-compose.yml)
