name: Docker build of nginx-keycloak

on: [push]

jobs:

  docker-build:
    name: Ubuntu 22.04 build of nginx-keycloak
    runs-on: ubuntu-22.04

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
            
      - name: Docker-compose build
        run: |
          docker compose build
